aliases:
    fleeks: cd ~/.local/share/fleek
allow_broken: false
auto_gc: false
bling: high
blocklist:
    - vscode
byo_git: false
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: true
    autopull: true
    autopush: true
    enabled: true
min_version: 0.8.4
name: Fleek Configuration
overlays: {}
packages:
    - helix
    - stack
    - gcc
    - unzip
    - ffmpeg
    - neofetch
    - neovim
    - lazygit
    - jq
    - btop
    - vifm
    - ripgrep
    - emacs
    - gdu
    - bottom
    - exif
    - gnumake
    - rustup
    - elixir
    - inotify-tools
    - nushell
    - volta
    - deno
    - bun
paths:
    - $HOME/bin
    - $HOME/.local/bin
    - $HOME/.volta/bin
    - $HOME/.config/emacs/bin
programs:
    - dircolors
    - nushell
shell: zsh
systems:
    - arch: x86_64
      home: ""
      hostname: DESKTOP-C9O7JV2
      os: linux
      user:
        email: sajkoooo@gmail.com
        name: alex argunov
        ssh_private_key_file: ""
        ssh_public_key_file: ""
        username: troglotit
      username: troglotit
    - arch: x86_64
      home: ""
      hostname: ntrn1703
      os: linux
      user:
        email: alexander.argunov@tern.ru
        name: aargunov
        ssh_private_key_file: ~/.ssh/id_ed25519
        ssh_public_key_file: ~/.ssh/id_ed25519.pub
        username: aargunov
      username: aargunov
track: ""
unfree: true
users:
    - email: sajkoooo@gmail.com
      name: alex argunov
      ssh_private_key_file: ""
      ssh_public_key_file: ""
      username: troglotit
    - email: alexander.argunov@tern.ru
      name: aargunov
      ssh_private_key_file: ~/.ssh/id_ed25519
      ssh_public_key_file: ~/.ssh/id_ed25519.pub
      username: aargunov
