aliases:
    fleeks: cd ~/.local/share/fleek
bling: default
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: true
    autopull: true
    autopush: true
    enabled: true
min_version: 0.8.4
name: Fleek Configuration
overlays: {}
packages:
    - helix
    - stack
    - gcc
    - unzip
    - ffmpeg
    - neofetch
    - cargo
    - neovim
    - lazygit
    - jq
    - yq
    - btop
paths:
    - $HOME/bin
    - $HOME/.local/bin
    - $HOME/.volta/bin
programs:
    - dircolors
    - fzf
    - exa
    - bat
    - vifm
shell: bash
systems:
    - arch: x86_64
      hostname: DESKTOP-C9O7JV2
      os: linux
      username: troglotit
    - arch: x86_64
      hostname: ntrn1703
      os: linux
      username: aargunov
unfree: true
users:
    - email: sajkoooo@gmail.com
      name: alex argunov
      ssh_private_key_file: ""
      ssh_public_key_file: ""
      username: troglotit
    - email: alexander.argunov@tern.ru
      name: aargunov
      ssh_private_key_file: ~/.ssh/id_ed25519
      ssh_public_key_file: ~/.ssh/id_ed25519.pub
      username: aargunov
