aliases:
    fleeks: cd ~/.local/share/fleek
bling: high
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: true
    autopull: true
    autopush: true
    enabled: true
min_version: 0.8.4
name: Fleek Configuration
overlays: {}
packages:
    - helix
    - stack
    - gcc
    - unzip
    - ffmpeg
paths:
    - $HOME/bin
    - $HOME/.local/bin
    - $HOME/.volta/bin
programs:
    - dircolors
shell: zsh
systems:
    - arch: x86_64
      hostname: DESKTOP-C9O7JV2
      os: linux
      username: troglotit
unfree: true
users:
    - email: sajkoooo@gmail.com
      name: alex argunov
      ssh_private_key_file: ""
      ssh_public_key_file: ""
      username: troglotit
